# optim
weight_decay: 0.0005
base_lr: 0.05
step: [10, 20, 30, 40]


# model
model: model.msg3d.Model
model_args:
  num_class: 2 #120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  
  
# training
num_epoch: 30
device: [0]
batch_size: 32
forward_batch_size: 16
test_batch_size: 16
nesterov: True


train_feeder_args:
  debug: False

test_feeder_args:
  debug: False
  
  
finetune: True 

ignore_weights: [fc.weight, fc.bias]

weights: ./msg3d_pretrained_weights/ntu120-xsub-joint.pt
#weights: ./exps/ED_loss_weighted/1/weights/weights.pt